FROM node:20
RUN mkdir app
WORKDIR app
COPY package.json .
COPY *.js .
RUN npm install
ENV CATALOGUE_PORT=8080 \
    CATALOGUE_HOST="cataloguecontainer" \
    REDIS_HOST="rediscontainer"
CMD [ "node", "server.js" ]
