FROM node:20
RUN mkdir app
WORKDIR app
COPY package.json .
COPY *.js .
RUN npm install
ENV MONGO="true" \
    MONGO_URL="mongodb://mongodbcontainer:27017/users" \
    REDIS_HOST="redis://rediscontainer:6379"
CMD [ "node", "server.js" ]
